services:
  app:
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile
      args:
        BUILD_TARGET: ./cmd/app
    env_file:
      - ./deployment/local/.env
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:17.3
    environment:
      PGDATA: /data/postgres
    env_file:
      - ./deployment/local/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d subscription_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: